### ISSUE TITLE
Can somebody add input (feature and label) data format in Readme?

### ISSUE THREAD

**Issue by eric-zhenhai** [kaniblu/pytorch-bilstmcrf#3]

**Comment by kaniblu** [comment]
Data format is rather simple: sentences are separated by \n and tokens are separated by spaces. Each feature should be specified in a new file. I will update README file for better clarification.

**Comment by EmilStenstrom** [comment]
@kaniblu The readme mentions the "NER task", but I see no description of how to send in the correct NER tags anywhere? The README only describes input sentences and POS tags, not the correct training examples.

(Maybe switching to IOB2 would be a better API for people to follow?)
