### ISSUE TITLE
No module named 'numpy.core.multiarray\r' on preprocess.py

### ISSUE THREAD

**Issue by dkarmon** [kaniblu/pytorch-bilstmcrf#6]
Hi,
The following exception raises while trying to run the preprocess.py file:

> data = pickle.load(open(args.pickle_path, "rb"), encoding="latin1")
> ModuleNotFoundError: No module named 'numpy.core.multiarray\r'
line 28 in preprocess.py
  
Please advise

OS: Windows 10
Python: 3.6.4 (anaconda)

**Comment by suzil** [comment]
`conda install numpy` or `pip install numpy`. It should be added to `requirements.txt`.
